# Generated by Django 2.1.2 on 2018-11-02 14:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_bannerlbt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('images', models.ImageField(blank=True, null=True, upload_to='goods/banner/', verbose_name='封面图')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='goods.Goods', verbose_name='商品类目')),
            ],
            options={
                'verbose_name': '商品轮播图',
                'verbose_name_plural': '商品轮播图',
            },
        ),
    ]
